type: 'baseline'
framework: 'tensorflow' # ['tensorflow', 'torch']
nfilters: [40, 40]
kernel_size: 3
pooling: [(1, 4), (1, 2)]
dropout: [0.3, 0.3]
top_flatten: 'avg'
spectrogram_dim: 64, 51, 1
verbose: True