type: 'baseline'
framework: 'tensorflow' # ['tensorflow', 'torch']
filters: [40, 40]
kernel: 3
pool: [(1, 10), (1, 10)]
dropout: [0.3, 0.3]
global_pool: 'avg'
spectrogram_dim: (64, 51, 1)
verbose: True